import fs from 'fs';
import path from 'path';

export function writeDebugFile(name: string, content: string | string[]): void {
  if (process.env.DEBUG !== 'true') return;

  const fileName = `${name}.debug.txt`;
  const fileContent = Array.isArray(content) ? content.join('\n') : content;
  fs.writeFileSync(fileName, fileContent);
}

export function writeTestFile(filePath: string, content: string): void {
  // Ensure the test file is marked as generated
  const marker = '// Generated by TestGen';
  const contentWithMarker = content.includes(marker)
    ? content
    : `${marker}\n${content}`;

  // Create directory if it doesn't exist
  const dir = path.dirname(filePath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  fs.writeFileSync(filePath, contentWithMarker);
}
